<a href="https://colab.research.google.com/github/denverkim/WEBCRAWLING/blob/main/LAB10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 붓꽃 데이터 열어서 확인
from sklearn import datasets

iris = datasets.load_iris()

print(iris.data)
print(iris.target)
print(iris.feature_names)
print(iris.target_names)

In [21]:
# 붓꽃데이터를 열어 타겟과 속성이름을 포함한 df 만들기

import pandas as pd

df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [22]:
# 컬럼이름 변경
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target']
df.head()

   sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [23]:
# 숫자로 된 범주를 글자로 바꾸기

df.target.replace(0, 'setosa', inplace=True)
df.target.replace(1, 'versicolor', inplace=True)
df.target.replace(2, 'virginica', inplace=True)

df.head()

/tmp/ipykernel_1073/2068174573.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.target.replace(0, 'setosa', inplace=True)

   sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [26]:
# 데이터프레임 요약

print(df.shape)
print(df.dtypes)
print(df.describe())
df.groupby('target').size()

(150, 5)
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
target           object
dtype: object
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

target
setosa        50
versicolor    50
virginica     50
dtype: int64

In [ ]:
# 데이터 타입 확인
df.dtypes

In [28]:
#X and y split. 독립, 종속변수 분리
y = df.target
x = df.drop('target', axis=1)

In [32]:
# 레이블 인코더
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [33]:
# 데이터셋 분리
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [35]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [44]:
#Decision Tree 의사결정트리
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
dt.score(x_test, y_test) #정확도

1.0

In [45]:
#Model evaluation (accuracy score) 모델평가
from sklearn.metrics import accuracy_score

y_pred = dt.predict(x_test)
accuracy_score(y_test, y_pred)

1.0

In [48]:
#5 fold cross validation (5 fold) 교차검증

from sklearn.model_selection import cross_val_score

dt_cv = cross_val_score(dt, x_test, y_test, cv=5)
dt_cv

array([1.        , 0.83333333, 1.        , 1.        , 1.        ])

In [ ]:
#Decision tree visualization (max depth=3) 의사결정트리 시각화

In [50]:
#Random Forest 랜덤포레스트

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

#Model evaluation (accuracy score) 모델평가
rf.predict(x_test)
accuracy_score(y_test, y_pred)

#5 fold cross validation (5 fold) 5배 교차검증
rf_cv = cross_val_score(rf, x_test, y_test, cv=5)
rf_cv

array([1.        , 0.83333333, 0.83333333, 1.        , 1.        ])