<a href="https://colab.research.google.com/github/denverkim/WEBCRAWLING/blob/main/LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
# 리스트
lst = [3,-5,7,4]
lst

[3, -5, 7, 4]

In [8]:
# 씨리즈
import pandas as pd

s = pd.Series([3,-5,7,4], index=['a', 'b', 'c', 'd'])
s
# s.mean()

a    3
b   -5
c    7
d    4
dtype: int64

In [14]:
# 딕셔너리로 데이터 프레임 만들기
dict = {'Country': ['Belgium', 'India', 'Brazil'],
        'Capital': ['Brussels', 'New Delhi', 'Brailia'],
        'Population':[11190846, 1303171035, 207847528]}
dict['Country'][0]
df = pd.DataFrame(dict)
df

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil    Brailia   207847528

In [16]:
df.Population.mean()

np.float64(507403136.3333333)

In [22]:
# 리스트로 데이터 프레임 만들기
data = [['Jan',58,42,74,22,2.95],
        ['Feb',61,45,78,26,3.02],
  ['Mar',65,48,84,25,2.34],
  ['Apr',67,50,92,28,1.02]]
data
pd.DataFrame(data, columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

  month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58       42           74          22               2.95
1   Feb        61       45           78          26               3.02
2   Mar        65       48           84          25               2.34
3   Apr        67       50           92          28               1.02

In [ ]:
data = [['Jan',58,42,74,22,2.95],
  ['Feb',61,45,78,26,3.02],
  ['Mar',65,48,84,25,2.34],
  ['Apr',67,50,92,28,1.02]]
df = pd.DataFrame(data, index = [0,1,2,3],
                  columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

In [25]:
# Create a data frame with your class information (courseID, courseName, creditHours, Days) and save it as an Excel file. 이번학기에 듣는 클래스의 정보를 이용하여 데이터프레임을 만드시오.
courses = {
    'couseID': [1111, 2222, 3333],
    'courseName': ['DM', 'web crawling', 'algorithm'],
    'creditHours': [3, 3, 3],
    'Days': ['Mon', 'Tues', 'Thur']
}
df = pd.DataFrame(courses)
df.to_excel('course.xlsx')

In [30]:
# 텍스트 파일 열기
weather = pd.read_csv('/content/weather.txt')
print(weather.head()) #상위 5개 데이터
print(weather.tail()) #하위 5개 데이터

  month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58       42           74          22               2.95
1   Feb        61       45           78          26               3.02
2   Mar        65       48           84          25               2.34
3   Apr        67       50           92          28               1.02
4   May        71       53           98          35               0.48
   month  avg_high  avg_low  record_high  record_low  avg_precipitation
7    Aug        77       59          102          43               0.03
8    Sep        77       57          103          40               0.17
9    Oct        73       54           96          34               0.81
10   Nov        64       48           84          30               1.70
11   Dec        58       42           73          21               2.56

In [31]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   month              12 non-null     object
 1   avg_high           12 non-null     int64
 2   avg_low            12 non-null     int64
 3   record_high        12 non-null     int64
 4   record_low         12 non-null     int64
 5   avg_precipitation  12 non-null     float64
dtypes: float64(1), int64(4), object(1)
memory usage: 708.0+ bytes

In [32]:
weather.shape

(12, 6)

In [33]:
weather.columns

Index(['month', 'avg_high', 'avg_low', 'record_high', 'record_low',
       'avg_precipitation'],
      dtype='object')

In [34]:
weather.index

RangeIndex(start=0, stop=12, step=1)

In [35]:
weather.ndim

2

In [36]:
weather.values

array([['Jan', 58, 42, 74, 22, 2.95],
       ['Feb', 61, 45, 78, 26, 3.02],
       ['Mar', 65, 48, 84, 25, 2.34],
       ['Apr', 67, 50, 92, 28, 1.02],
       ['May', 71, 53, 98, 35, 0.48],
       ['Jun', 75, 56, 107, 41, 0.11],
       ['Jul', 77, 58, 105, 44, 0.0],
       ['Aug', 77, 59, 102, 43, 0.03],
       ['Sep', 77, 57, 103, 40, 0.17],
       ['Oct', 73, 54, 96, 34, 0.81],
       ['Nov', 64, 48, 84, 30, 1.7],
       ['Dec', 58, 42, 73, 21, 2.56]], dtype=object)

In [37]:
weather.dtypes

month                 object
avg_high               int64
avg_low                int64
record_high            int64
record_low             int64
avg_precipitation    float64
dtype: object

In [38]:
weather.describe()

        avg_high    avg_low  record_high  record_low  avg_precipitation
count  12.000000  12.000000    12.000000   12.000000          12.000000
mean   68.583333  51.000000    91.333333   32.416667           1.265833
std     7.366488   6.060303    12.323911    8.240238           1.186396
min    58.000000  42.000000    73.000000   21.000000           0.000000
25%    63.250000  47.250000    82.500000   25.750000           0.155000
50%    69.000000  51.500000    94.000000   32.000000           0.915000
75%    75.500000  56.250000   102.250000   40.250000           2.395000
max    77.000000  59.000000   107.000000   44.000000           3.020000

In [41]:
weather.avg_high.mean()

np.float64(68.58333333333333)

In [43]:
weather.sort_values('avg_precipitation', ascending=False)

   month  avg_high  avg_low  record_high  record_low  avg_precipitation
1    Feb        61       45           78          26               3.02
0    Jan        58       42           74          22               2.95
11   Dec        58       42           73          21               2.56
2    Mar        65       48           84          25               2.34
10   Nov        64       48           84          30               1.70
3    Apr        67       50           92          28               1.02
9    Oct        73       54           96          34               0.81
4    May        71       53           98          35               0.48
8    Sep        77       57          103          40               0.17
5    Jun        75       56          107          41               0.11
7    Aug        77       59          102          43               0.03
6    Jul        77       58          105          44               0.00

In [46]:
# 컬럼 선택
weather['avg_high']
weather.avg_high
weather[['avg_high','avg_low']]

    avg_high  avg_low
0         58       42
1         61       45
2         65       48
3         67       50
4         71       53
5         75       56
6         77       58
7         77       59
8         77       57
9         73       54
10        64       48
11        58       42

In [50]:
# Slice the records and display the following columns and rows:
# 레코드를 짤라서 다음의 열과 행을 출력
# avg_low
weather.avg_low
# §Rows 1 to 2
weather.iloc[0:2]
# §avg_low and avg_high

# §9 row of avg_precipitation column
weather.avg_precipitation[8]
# §4 to 5 rows of 1 and 4 columns
weather.iloc[3:5, [0, 3]]

  month  record_high
3   Apr           92
4   May           98

In [58]:
# §Filter the data and display the following columns and rows:
# 데이터를 검색하여 다음의 열과 행을 출력
# §avg_precipitation > 1.0
w1 = weather[weather.avg_precipitation>1]

# §Month is in either June, July, or August
weather[weather.month.isin(['Jun', 'Jul', 'Aug'])]

  month  avg_high  avg_low  record_high  record_low  avg_precipitation
5   Jun        75       56          107          41               0.11
6   Jul        77       58          105          44               0.00
7   Aug        77       59          102          43               0.03

In [62]:
# §Assign new values in the following locations:
# §101.3 for avg_precipitation column at index 9
weather.loc[9, 'avg_precipitation'] = 101.3
# §Np null values for avg_precipitation column at index 9 (np.nan)
# §5 for all rows in avg_low column avg_low 컬럼 전체를 5로 바꾸기
weather.avg_low = 5
weather
# §Add new column named avg_day that is the average of avg_low and avg_high avg_low와 avg_high의 평균을 구하여 avg_day컬럼을 만
weather['avg_day'] = weather.avg_low + weather.avg_high / 2
weather

,month,avg_high,avg_low,record_high,record_low,avg_precipitation,avg_day
0,Jan,58,5,74,22,2.95,34.0
1,Feb,61,5,78,26,3.02,35.5
2,Mar,65,5,84,25,2.34,37.5
3,Apr,67,5,92,28,1.02,38.5
4,May,71,5,98,35,0.48,40.5
5,Jun,75,5,107,41,0.11,42.5
6,Jul,77,5,105,44,0.00,43.5
7,Aug,77,5,102,43,0.03,43.5
8,Sep,77,5,103,40,0.17,43.5
9,Oct,73,5,96,34,101.30,41.5
10,Nov,64,5,84,30,1.70,37.0
11,Dec,58,5,73,21,2.56,34.0