<a href="https://colab.research.google.com/github/denverkim/WEBCRAWLING/blob/main/LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Read weather.txt file into a dataframe.
import pandas as pd

weather = pd.read_csv('/content/weather.txt')
weather

# Print first 5 or last 3 rows of df 처음 다섯줄, 마지막 세줄 출력
print('상위 5개 레코드')
print(weather.head())

print('하위 3개 레코드')
print(weather.tail(3))

# Get data types, index, columns, values 데이터타입, 인덱스, 컬럼들, 값들

print('데이터타입')
print(weather.dtypes)

print('인덱스')
print(weather.index)

print('컬럼들')
print(weather.columns)

print('값들')
print(weather.values)

# Get statistical summary of each column
# Statistical summary of each column 각 컬럼에 대한 통계요약
print  ('통계요약')
print(weather.describe())

# Sort records by any column (descending order)
print('한 컬럼을 정해 내림차순으로 정렬')
print(weather.sort_values('avg_precipitation', ascending=False))

상위 5개 레코드
  month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58       42           74          22               2.95
1   Feb        61       45           78          26               3.02
2   Mar        65       48           84          25               2.34
3   Apr        67       50           92          28               1.02
4   May        71       53           98          35               0.48
하위 3개 레코드
   month  avg_high  avg_low  record_high  record_low  avg_precipitation
9    Oct        73       54           96          34               0.81
10   Nov        64       48           84          30               1.70
11   Dec        58       42           73          21               2.56
데이터타입
month                 object
avg_high               int64
avg_low                int64
record_high            int64
record_low             int64
avg_precipitation    float64
dtype: object
인덱스
RangeIndex(start=0, stop=12, step=1)
컬럼들
Index(['month', 'avg_high', 'avg_low', 'record_high', 'record_low',
       'avg_precipitation'],
      dtype='object')
값들
[['Jan' 58 42 74 22 2.95]
 ['Feb' 61 45 78 26 3.02]
 ['Mar' 65 48 84 25 2.34]
 ['Apr' 67 50 92 28 1.02]
 ['May' 71 53 98 35 0.48]
 ['Jun' 75 56 107 41 0.11]
 ['Jul' 77 58 105 44 0.0]
 ['Aug' 77 59 102 43 0.03]
 ['Sep' 77 57 103 40 0.17]
 ['Oct' 73 54 96 34 0.81]
 ['Nov' 64 48 84 30 1.7]
 ['Dec' 58 42 73 21 2.56]]
통계요약
한 컬럼을 정해 내림차순으로 정렬

   month  avg_high  avg_low  record_high  record_low  avg_precipitation
1    Feb        61       45           78          26               3.02
0    Jan        58       42           74          22               2.95
11   Dec        58       42           73          21               2.56
2    Mar        65       48           84          25               2.34
10   Nov        64       48           84          30               1.70
3    Apr        67       50           92          28               1.02
9    Oct        73       54           96          34               0.81
4    May        71       53           98          35               0.48
8    Sep        77       57          103          40               0.17
5    Jun        75       56          107          41               0.11
7    Aug        77       59          102          43               0.03
6    Jul        77       58          105          44               0.00

In [18]:
# Slice the records and display the following columns and rows:
# 레코드를 짤라서 다음의 열과 행을 출력
# avg_low
print(weather.avg_low)
# Rows 1 to 2

print(weather[:2])
# avg_low and avg_high
print(weather[['avg_low', 'avg_high']])

# 9 row of avg_precipitation column
print(weather.loc[8, 'avg_precipitation'])

# 4 to 5 rows of 1 and 4 columns
weather.iloc[3:5, [0, 3]]

0     42
1     45
2     48
3     50
4     53
5     56
6     58
7     59
8     57
9     54
10    48
11    42
Name: avg_low, dtype: int64
  month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58       42           74          22               2.95
1   Feb        61       45           78          26               3.02
    avg_low  avg_high
0        42        58
1        45        61
2        48        65
3        50        67
4        53        71
5        56        75
6        58        77
7        59        77
8        57        77
9        54        73
10       48        64
11       42        58
0.17

  month  record_high
3   Apr           92
4   May           98

In [23]:
# Filter the data and display the following columns and rows:
# 데이터를 검색하여 다음의 열과 행을 출력
# avg_precipitation > 1.0

weather[weather.avg_precipitation > 1.0]
# Month is in either June, July, or August

weather[weather.month.isin(['Jun', 'Jul', 'Aug'])]

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7      True
8     False
9     False
10    False
11    False
Name: month, dtype: bool

In [34]:
# Assign new values in the following locations:
# 101.3 for avg_precipitation column at index 9
weather.loc[9, 'avg_precipitation'] = 101.3

# Np null values for avg_precipitation column at index 9 (np.nan)
import numpy as np

weather.loc[9, 'avg_precipitation'] = np.nan

# 5 for all rows in avg_low column avg_low 컬럼 전체를 5로 바꾸기
weather.avg_low = 5

# Add new column named avg_day that is the average of avg_low and avg_high avg_low와 avg_high의 평균을 구하여 avg_day컬럼을 만듬
weather['avg_day'] = (weather.avg_low + weather.avg_high) / 2
weather

,month,avg_high,avg_low,record_high,record_low,avg_precipitation,avg_day
0,Jan,58,5,74,22,2.95,31.5
1,Feb,61,5,78,26,3.02,33.0
2,Mar,65,5,84,25,2.34,35.0
3,Apr,67,5,92,28,1.02,36.0
4,May,71,5,98,35,0.48,38.0
5,Jun,75,5,107,41,0.11,40.0
6,Jul,77,5,105,44,0.00,41.0
7,Aug,77,5,102,43,0.03,41.0
8,Sep,77,5,103,40,0.17,41.0
9,Oct,73,5,96,34,NaN,39.0
10,Nov,64,5,84,30,1.70,34.5
11,Dec,58,5,73,21,2.56,31.5

In [42]:
# Rename columns 컬럼이름 바꾸기
# avg_precipitation to avg_rain
weather = weather.rename(columns={'avg_precipitation': 'avg_rain'})
weather
# Change columns’ name to 'month','av_hi','av_lo','rec_hi','rec_lo','av_rain‘, ‘av_day’
weather.columns = ['month', 'av_hi', 'av_lo', 'rec_hi', 'rec_lo', 'av_rain', 'av_day']

# Save the result data frame to a csv file 데이터플레임을 csv파일로 저장
weather.to_csv('/content/weather.csv')