<a href="https://colab.research.google.com/github/denverkim/WEBCRAWLING/blob/main/LAB5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MERGE로 데이터 병합

In [1]:
import pandas as pd
left = pd.DataFrame({ 'id':[1,2,3,4,5],
                     'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
                     'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame( {'id':[1,2,3,4,5],
                       'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
                       'subject_id':['sub2','sub4','sub3','sub6','sub5']})

In [2]:
left

   id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5

In [3]:
right

   id   Name subject_id
0   1  Billy       sub2
1   2  Brian       sub4
2   3   Bran       sub3
3   4  Bryce       sub6
4   5  Betty       sub5

In [4]:
pd.merge(left, right, on='subject_id', how='left')

   id_x  Name_x subject_id  id_y Name_y
0     1    Alex       sub1   NaN    NaN
1     2     Amy       sub2   1.0  Billy
2     3   Allen       sub4   2.0  Brian
3     4   Alice       sub6   4.0  Bryce
4     5  Ayoung       sub5   5.0  Betty

In [5]:
pd.merge(left, right, on='subject_id', how='right')

   id_x  Name_x subject_id  id_y Name_y
0   2.0     Amy       sub2     1  Billy
1   3.0   Allen       sub4     2  Brian
2   NaN     NaN       sub3     3   Bran
3   4.0   Alice       sub6     4  Bryce
4   5.0  Ayoung       sub5     5  Betty

In [6]:
pd.merge(left, right, on='subject_id', how='outer')

   id_x  Name_x subject_id  id_y Name_y
0   1.0    Alex       sub1   NaN    NaN
1   2.0     Amy       sub2   1.0  Billy
2   NaN     NaN       sub3   3.0   Bran
3   3.0   Allen       sub4   2.0  Brian
4   5.0  Ayoung       sub5   5.0  Betty
5   4.0   Alice       sub6   4.0  Bryce

In [7]:
pd.merge(left, right, on='subject_id')

   id_x  Name_x subject_id  id_y Name_y
0     2     Amy       sub2     1  Billy
1     3   Allen       sub4     2  Brian
2     4   Alice       sub6     4  Bryce
3     5  Ayoung       sub5     5  Betty

In [8]:
pd.merge(left, right, on=['subject_id', 'id'])

   id  Name_x subject_id Name_y
0   4   Alice       sub6  Bryce
1   5  Ayoung       sub5  Betty

# CONCAT으로 데이터 합치기

In [9]:
df1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])
df2 = pd.DataFrame([['c', 3], ['d', 4]], columns=['letter', 'number'])

In [10]:
df1

  letter  number
0      a       1
1      b       2

In [11]:
df2

  letter  number
0      c       3
1      d       4

In [12]:
pd.concat([df1, df2]) #위아래로 concat

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [13]:
pd.concat([df1, df2], axis=1) #왼쪽 오른쪽 concat

  letter  number letter  number
0      a       1      c       3
1      b       2      d       4

# 슬라이드 11번

In [15]:
# 다음 파일을 읽고 데이터 병합을 수행 하시오(https://github.com/sehakflower/data/blob/main/titanic_1309.xlsx?raw=true)
titanic = pd.read_excel('https://github.com/sehakflower/data/blob/main/titanic_1309.xlsx?raw=true')

In [20]:
# 데이터 붙이기
# 상위 1000행을 train으로 나머지 행을 test로 저장
train = titanic[:1000]
test = titanic[1000:]

# train, test 위아래로 붙이기
# train, test 옆으로 붙이기

# 데이터 병합
# name, pclass, sex, age를 df1(상위 1000행)으로 name, survived를 df2(하위 500행)로 저장
df1 = train[['name', 'pclass', 'sex', 'age']].head(1000)
df2 = test[['name', 'survived']].tail(500)

# name 으로 inner join
# name 으로 outer join
# name 으로 left join
# name 으로 right join
df2

                                name  survived
1000    McCormack, Mr. Thomas Joseph         1
1001              McCoy, Miss. Agnes         1
1002             McCoy, Miss. Alicia         1
1003              McCoy, Mr. Bernard         1
1004  McDermott, Miss. Brigdet Delia         1
...                              ...       ...
1304            Zabour, Miss. Hileni         0
1305           Zabour, Miss. Thamine         0
1306       Zakarian, Mr. Mapriededer         0
1307             Zakarian, Mr. Ortin         0
1308              Zimmerman, Mr. Leo         0

[309 rows x 2 columns]